name = "riell-mail-email-handler"
main = "index.js"
compatibility_date = "2024-09-01"

[vars]
RIELL_MAIL_WEBHOOK_URL = "https://riellpediamail.vercel.app/api/internal/email/incoming"
EMAIL_HANDLER_SECRET = "cf_worker_webhook_secret_riellmail_2026_xyz"
